### ISSUE TITLE
Form Components

### ISSUE THREAD

**Issue by colinramsay** [touchstonejs/touchstonejs#1]
I hope you don't mind me using your issue list as a placeholder for the things I'd like to see! Regarding forms there needs to be:

- Textfield
- Textarea
- Checkbox/toggle
- Select & multiselect
- Date and Time
- Disabled/readonly states

Is this on your hitlist? Would be good to see a roadmap on the wiki too. I'll be free in the new year to spend some time on this I think and having a list of priorities might be handy.

**Comment by zkilgore** [comment]
Hey @JedWatson, first off, this framework is looking awesome! Really looking forward to watching it continue to develop.

I was playing around with the demo on my phone, and noticed on the form page when tabbing or tapping between inputs there's a pretty gnarly jump where the cursor as well as the view is out of sync with the element you're trying to type in. Have you noticed that/do you any idea why that is happening?

**Comment by JedWatson** [comment]
@zkilgore Thanks!

Re: the keyboard jankiness, we've been working on that one.

It's related to the default "scroll on focus" and "keyboard shrinks view" behaviour(s) in iOS. Cordova has a patchy history with this (used to be a core feature, then a plugin which was abandoned, now there are two popular plugins that do _slightly_ different things)

Will update as soon as we've got it solved. Also planning to put together a knowledgeable of how to set up your cordova project (e.g. recommended plugins and settings, etc.)

**Comment by zkilgore** [comment]
@JedWatson That's what I was thinking it was. Well, something like that at least!

I am currently writing a form heavy piece of an app now, so if you guys have any specific leads that you just don't have the bandwidth to work on, I'd be more than happy to help out and help squash this.

**Comment by jossmac** [comment]
These components/issues have been added/resolved either in Touchstone itself or by other React components
