### ISSUE TITLE
Loading Spinner background disappears in Chrome after view transition

### ISSUE THREAD

**Issue by molomby** [touchstonejs/touchstonejs#10]
Regarding the demos at http://touchstonejs.io/ ..

The modal loading option works correctly at first but after triggering a transition (by clicking into another demo), it partially fails (see screenshot). This bug is doesn't occur after using the "Modal message" demo.

Tested in Chrome 40.0.2214.28 beta-m on Windows Server 2008 R2.

![screenshot](https://cloud.githubusercontent.com/assets/2416367/5406037/a4b4250e-8201-11e4-9246-6f845a74e9c8.png)

**Comment by jossmac** [comment]
Fixed
