### ISSUE TITLE
0.7.0 in npm installation issue

### ISSUE THREAD

**Issue by zoechen799** [touchstonejs/touchstonejs#100]
Hi, 
  I tried to install 0.7.0 from npm, but the lib folder is missing after install. Can anyone help?

**Comment by aayushkapoor206** [comment]
There's no lib folder

**Comment by zoechen799** [comment]
@aayushkapoor206, then when I import {ViewManager} from 'touchstonejs'; there's an error there while compiling with webpack.

**Comment by zoechen799** [comment]
@JedWatson  Hi, I'm using touchstonejs with react0.14.3, which needs the newest version on npm: 0.7.0. while I'm using webpack to run the project, it warns that the module 'ViewManager' can't be found. I noticed that the lib folder inside touchstone 0.6.0's is missing from 0.7.0. Is it a issue? Or should I do something else to support touchstone 0.7.0? Thanks!

**Comment by JedWatson** [comment]
Sorry @zoechen799 and @aayushkapoor206 - it looks like the build wasn't included in that release (!)

I've added a `prepublish` script so this doesn't happen again and pushed a new version `0.7.1`

**Comment by zoechen799** [comment]
Thanks a lot!
