### ISSUE TITLE
Instant transitions and popin transitions broken on 0.7.3

### ISSUE THREAD

**Issue by soualid** [touchstonejs/touchstonejs#115]
Hello,

I am evaluating TouchstoneJS for my mobile app, and just discovered that all the "instant" transitions flickers using the latest version, I have seen a PR concerning this issue (https://github.com/touchstonejs/touchstonejs/pull/110) but another issue that may be related is the disappear transition of the Popin component that plays the "appear" transition instead of the "disappear" one.

Curiously, this issue does not appear on the http://touchstonejs.github.io/touchstonejs-starter/ demo.

**Comment by soualid** [comment]
If anybody wonder how to fix this issue, just reduce `animation-duration` for `.Popup-dialog-leave` in `Popup.less` to 140ms.

The PR mentioned in my first message fix the "instant" transitions issue.

**Comment by JedWatson** [comment]
@soualid thanks for the info, I've just merged that PR and will release a new version shortly.

Can you clarify what you mean about the animation for `.Popup-dialog-leave` needing to be 140ms? It's already set to that: https://github.com/touchstonejs/touchstonejs/blob/master/less/components/Popup.less#L34

**Comment by soualid** [comment]
Sorry, I reversed the `diff`, I had to change both `enter-active` and `leave` animations duration to 320ms to make it works correctly (was testing it out using latest version of chrome on desktop/osx).
