### ISSUE TITLE
How do you manage top level state passed as props to components managed by a ViewContainer's Views?

### ISSUE THREAD

**Issue by jmflannery** [touchstonejs/touchstonejs#117]
For example, this snippet is from the render method of the App component in app.js of the starter project:

    <ViewManager name="app" defaultView="main">
        <View name="main" component={MainViewController} />
        <View name="transitions-target-over" component={require('./views/transitions-target-over')} />
    </ViewManager>
I need to pass state to the MainViewController controller as props like this:

    <ViewManager name="app" defaultView="main">
        <View name="main" component={MainViewController} api_token={this.state.api_token} update_token={this.update_token} />
        <View name="transitions-target-over" component={require('./views/transitions-target-over')} />
    </ViewManager>

in the App component I've added a `getInitialState` method:
    
    getInitialState () {
        return {
            api_token: 'initial_token'
        }
    }

and an `update_token` method:

    update_token (token) {
        console.log('updating token: ' + token);
        this.setState({ api_token: token });
    }

For testing purposes I added `componentDidMount` and `componentWillReceiveProps` methods to the `MainViewController`:

    componentDidMount () {
        console.log('componentDidMount:')
        console.log('token: ' + this.props.api_token);
        this.props.update_token('new_token');
    },

    componentWillReceiveProps (nextProps) {
        console.log('componentWillReceiveProps:');
        console.log('Next token: ' + nextProps.api_token);
        console.log('Old token: ' + this.props.api_token);
    },
I also added a bit of logging added to the top the the `MainViewController` `render` method:
   
    console.log('render:')
    console.log('token: ' + this.props.api_token);

It does not seem to pass the new state down to the `MainViewController`. The `update_token` callback function is called, calling `setState`, which is triggering a re-render, however the `MainViewController` is not receiving the new props, it is retaining the old. Here is the output:

    render:
    token: initial_token
    componentDidMount:
    token: initial_token
    updating token: new_token
    componentWillReceiveProps:
    Next token: initial_token
    Old token: initial_token
    render:
    token: initial_token

My understanding is that this is a common pattern in react to pass state to child components. Is this expected to work this way?

Thanks!

**Comment by gotoAndBliss** [comment]
+1

**Comment by JedWatson** [comment]
Fixed by #118
