### ISSUE TITLE
Taps can incorrectly pass through to the next view after a transition

### ISSUE THREAD

**Issue by JedWatson** [touchstonejs/touchstonejs#15]
We handle tap events with `react-tappable`, which fires an event after detecting a `touchstart` / `touchend` combination. Sometimes, WebKit also fires a click event after 300ms. This is automatically blocked from firing additional tap events on other `tappable` elements.

Unfortunately other components that natively respond to the click event may still do so during a view transition, incorrectly focusing a field or causing other unexpected behaviour.

Probably the best workaround for this is to display a blocking element (transparent div) over the entire UI during transitions that captures the subsequent click event, although I'd love to hear any other ideas on how we can handle this.

**Comment by dcousens** [comment]
@JedWatson any updates?

**Comment by jossmac** [comment]
This has since been resolved in [react-tappable](https://github.com/JedWatson/react-tappable)
