### ISSUE TITLE
Approach to state in components

### ISSUE THREAD

**Issue by ivan-kleshnin** [touchstonejs/touchstonejs#19]
I know a little about React but, if I'm right, there is two fundamental approaches to state. First is to keep state within components and second is to pull all state to one global object (pseudo-database). First approach is the simplest at start but have many drawbacks as application grows. As state is scattered, general tasks like making history of all actions are a hell. With second approach one can easily store and restore state with one single (and generic!) function, switch storage strategy (replace native objects with frontend DB like DataScript) and so on. React docs recommend to use "as little stateful components as possible" but it's quite obvious that it's possible to reduce state to just one application component. Sure it's also possible to create something in between... but that would clearly be the worst of options.

I reviewed your code a bit and it discovered that most of **touchstone** components are stateless, except those two:
* `LabelSelect`
* `Passcode`

Let me question why `Input` and `Select` should be anything different in this matter. 
Yes, it's may be just an artefact of dev. state or something, but I'd like to be sure with your opinion on this. Explicitly declared intentions and decisions are very helpful, thats why we create roadmaps etc.

**Comment by jossmac** [comment]
@ivan-kleshnin great catch!

Sorry it took me so long to get back to you on this. The state in `LabelSelect` was, as you say, an artefact of dev. The state in `Passcode` is, as far as I can remember, unavoidable - ping @dcousens for confirmation.

The `Passcode` component was built for http://www.ei8ht.com.au and probably shouldn't have made its way into Touchstone core. Unfortunately at the time we were moving very quickly and trying to release :disappointed: 

You may have noticed the [touchstonejs-ui](https://github.com/touchstonejs/touchstonejs-ui) repo, which is where we intend to move all the UI components when we have time. This migration will include a bunch of cleanup and possibly a transition to CSS in JS. `Passcode` will likely be removed at this point with a major version bump so those using it in the wild don't get burnt.

Hope that helps!

**Comment by ivan-kleshnin** [comment]
> Hope that helps!

Thanks! I will take a look to this again.
