### ISSUE TITLE
Form components should inherit props

### ISSUE THREAD

**Issue by jossmac** [touchstonejs/touchstonejs#26]

**Comment by dcousens** [comment]
Relevant to the mess that is https://github.com/JedWatson/touchstonejs/pull/27

**Comment by dcousens** [comment]
@jossmac is there any components that still need this?

**Comment by jossmac** [comment]
@dcousens all components should use blacklist and {...props}

I think we have a best practice, just need to implement it

**Comment by jossmac** [comment]
Hmm, perhaps we should follow the React.js docs: `var { omitThisProp, ...other } = this.props;` then use as `<Component {...other} />`

Via https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx

**Comment by dcousens** [comment]
@jossmac that is a good solution.

**Comment by dcousens** [comment]
@jossmac why couldn't we use this again?

**Comment by jossmac** [comment]
Something about a bug with Babel/Browserify I think

**Comment by dcousens** [comment]
Ok.

Closing as this has been done properly across most components now.
