### ISSUE TITLE
View context

### ISSUE THREAD

**Issue by jossmac** [touchstonejs/touchstonejs#28]
It'd be handy to have a global variable for the previous view, something you can access like  `this.context.app.prevView`

**Comment by arnold-almeida** [comment]
A React "Context" seems like the best way forward but its not properly implemented as yet.

See : 
 - https://facebook.github.io/react/blog/2014/03/28/the-road-to-1.0.html#context
 - https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html

**Comment by dcousens** [comment]
A previous view is not even guaranteed to exist,  and is a concept that should only be meaningful in the context of a history manager.
Touchstone is not a history manager, and at most, will eventually link to an easily pluggable component/module that you can use to manage this for you.
