### ISSUE TITLE
In page demo on touchstonejs.io is not contained in iPhone container in portrait view

### ISSUE THREAD

**Issue by kevinold** [touchstonejs/touchstonejs#31]
View of the touchstonejs.io homepage on my iPad when in portrait view.  I'll see if I can get a fix for it in the next day or two.

![img_0070](https://cloud.githubusercontent.com/assets/21967/6006516/b50fa252-aad8-11e4-9514-1b83d1edf9f4.PNG)

**Comment by jossmac** [comment]
No longer relevant
