### ISSUE TITLE
Transfer of ref to input subcomponent doesn't seem to work.

### ISSUE THREAD

**Issue by zenlambda** [touchstonejs/touchstonejs#34]
Were you trying to allow the component ref to be transferred to the input element? It would be nice if it were possible to get an input value using a ref but the transfer of refs (if that's what's supposed to happen in this code) doesn't seem to work.

https://github.com/JedWatson/touchstonejs/blob/master/lib/ui/Input.js#L35

If you try to print this.props.ref in the render method you can see that it is undefined.

**Comment by zenlambda** [comment]
In fact it might be more usable to have a fixed ref of 'input'. If absolutely necessary the name of the ref could be a property called inputRef which defaults to 'input'.

So in your form you would always reference it as follows:

```
var email = this.refs.email.refs.input.getDOMNode().value;
```

Alternatively a helper method could be added to the Input component to shorten the above to:

```
var email =  this.refs.email.getValue();
```

**Comment by dcousens** [comment]
This is a react feature.  Refs are not exposed beyond the parent they were defined in.  It was a bug for us to have this feature in the first place, because it simply does not work.

Apologies @zenlambda.
