### ISSUE TITLE
Slide to animation seems to be bugged in iOS 8.1.3 Safari

### ISSUE THREAD

**Issue by digitaltoad** [touchstonejs/touchstonejs#35]
When viewing the demo at http://demo.touchstonejs.io, I noticed that the animation to an area does not render, but the animation from that area does. This seems to happen on any sliding/revealing animations, but not fades.

**Comment by jossmac** [comment]
Hi @digitaltoad, thank you for your contribution.

This issue is very frustrating as it only presents on mobile safari. To see the desired behaviour please view the site on a desktop/laptop browser. Better yet, build the demo app to your device for silky smooth transitions.

**Comment by jossmac** [comment]
Fixed with v0.5.0
