### ISSUE TITLE
Scrolling issue on Windows Phone

### ISSUE THREAD

**Issue by luisrudge** [touchstonejs/touchstonejs#36]
![touchstone-scroll](https://cloud.githubusercontent.com/assets/941075/6170107/4b13c412-b2b9-11e4-88c0-98fcadcf1522.gif)

**Comment by luisrudge** [comment]
any thoughts?

**Comment by morenoh149** [comment]
jed mentioned they'd get a windows phone to test touchstone on. I'd check back after then.

**Comment by luisrudge** [comment]
I know it's not perfect, but you can download an Windows virtual machine [here](https://www.modern.ie/en-us/virtualization-tools#downloads) and download a free version of visual studio [here](http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx). The vs comes with the windows phone SDK and emulator.

Thanks!

**Comment by luisrudge** [comment]
Oh, I can help too, if you want. I'm just not sure what to look for.

**Comment by jossmac** [comment]
I'm not 100%, but i think this is browser specific. Would you mind building the cordova app to your phone and testing it?

Make sure you have this preference `<preference name="DisallowOverscroll" value="true"/>` in your config.xml

**Comment by luisrudge** [comment]
I tested on the online demo, not using cordova. I also don't have any of the tools to do that right now.

**Comment by jossmac** [comment]
Hi @luisrudge,

We've made significant changes to Touchstone since this was logged, there's also been many improvements to [react-tappable](https://github.com/JedWatson/react-tappable).

Would you mind going to https://touchstonejs.github.io/touchstonejs-starter and seeing if you can replicate?

**Comment by SOSANA** [comment]
@jossmac your on fire, welcome back :)

**Comment by luisrudge** [comment]
Hi. I tested on the new Microsoft Edge (Windows Mobile @ preview) and it works great!

**Comment by jossmac** [comment]
Fantastic!

Thanks for getting back to us on that, and so quickly :smile:
