### ISSUE TITLE
Hot-reload for development

### ISSUE THREAD

**Issue by zenlambda** [touchstonejs/touchstonejs#37]
Could we support hot reload to provide 'immediate-feedback' development environment?

Similar to: 

http://gaearon.github.io/react-hot-loader/

Would we need to transition to webpack (I understand this is a requirement for hot loader - above)? Would there be a downside to using webpack over browserify?

**Comment by jossmac** [comment]
@amay0048 do you have ideas on this?

**Comment by amay0048** [comment]
Yep, we found the ionic command line code that we should be able to port to this. I'll have a look at it

**Comment by dcousens** [comment]
The site in this repository now has `livereload` enabled for development.
If you want this for the development of your own projects,  please use https://github.com/touchstonejs/touchstonejs-tasks.
