### ISSUE TITLE
Prebuild jsx before releasing to NPM

### ISSUE THREAD

**Issue by lazywei** [touchstonejs/touchstonejs#47]
Hi,

I notice that there are some jsx syntaxes in `createApp.js`, and it causes me some problems when I try to load it via CommonJS style (webpack, actually). I think it makes more sense to prebuild these jsx into pure js before relasing to npm. How do you think?
Thanks.

**Comment by JedWatson** [comment]
:+1: we should do this.

**Comment by dcousens** [comment]
Is currently the case.

The amount of support code to make everything work with both build systems is insane.
For example, if we just dropped all support for `CommonJS` and just supported browserify,  we wouldn't even need a gulp file beyond the live development server. 
The transforms would be simply defined,  and all controlled at the top level.
