### ISSUE TITLE
FlexLayouts and Swiper.js

### ISSUE THREAD

**Issue by KeKs0r** [touchstonejs/touchstonejs#49]
Hi,

I am trying to build the new version of my app with touchstone and I am loving it so far. I am completely aware that it is still in a very early stage. I wanted to swiper.js in order to build a subnavigation for on of my views. Unfortunately the swiper.js containers do not seem to work with the Flexlayout.

Is there a plan to build a swiper component for touchstone itself? If not I am willing to build one, based on swiper.js if others are interested and somebody can lead me into the right direction.

Here is my current approach:
```javascript
module.exports = React.createClass({
    displayName: "swiper_view",
    getInitialState: function(){
        return {
            activeSlide: 0
        }
    },
    componentDidMount: function() {
        var self = this;
        this.swiper = new Swiper (this.refs.swiper.getDOMNode(), {
            direction: 'horizontal',
            loop: false,
            onSlideChangeEnd: self._onSlideChangeEnd
        });
    },
    _onSlideChangeEnd: function(swiper){
       this.setState({activeSlide: swiper.activeIndex});
    },
    _handleToggle: function(slide){
        this.swiper.slideTo(slide);
    },
    render: function(){
        return (
            <UI.FlexLayout className={this.props.viewClassName}>
                <UI.Headerbar label="Swiper Container" />
                <UI.Headerbar height="36px" className="Subheader">
                    <UI.Toggle value={this.state.activeSlide} onChange={this._handleToggle} options={[
                        { label: 'Slide 1', value: 0 },
                        { label: 'Slide 2', value: 1 },
                        { label: 'Slide 3', value: 2 }
                    ]} />
                </UI.Headerbar>
                <UI.FlexBlock grow>
                    <div className="swiper-container" ref="swiper">
                        <div className="swiper-wrapper">
                            <div className="swiper-slide">
                                <UI.FlexBlock scrollable grow >
                                    This is the main container that should show content and be scrollable!
                                    Content can be very long!
                                </UI.FlexBlock>
                            </div>
                            <div className="swiper-slide">
                                <UI.FlexBlock scrollable grow >
                                    This is the content of the second slide, which can be reached by clicking on the
                                    subnavigation or swiping on the screen.
                                    <br /><br /> <br /><br /><br /> <br />
                                    Now more content
                                    <br /><br /> <br /><br /><br /> <br />
                                    And more!
                                </UI.FlexBlock>
                            </div>
                            <div className="swiper-slide">
                                <UI.FlexBlock scrollable grow >
                                    Last Slide
                                </UI.FlexBlock>
                            </div>
                        </div>
                    </div>
                   <UI.Footerbar height="50px" type="default">
                      <UI.FooterbarButton icon="ion-trophy" disabled />
                      <UI.FooterbarButton icon="ion-earth" />
                      <UI.FooterbarButton icon="ion-bag" />
                      <UI.FooterbarButton icon="ion-ios7-person" />
                      <UI.FooterbarButton icon="ion-more" />
                  </UI.Footerbar>
                </UI.FlexBlock>
            </UI.FlexLayout>
        );
    }
});
```

The Problem with it is, that within the different slides, the scrolling flexbox is not working. Even if there is more content I cant scroll, although the scrollbar is visible.

**Comment by giantelk** [comment]
Also take a look at react-carousel, and react-touch, on github. React-touch
uses the Zynga scroller, it's the best javascrit lib I've seen for swiping
and scrolling.

There is also react-swipe. But Zynga is best Imo:
https://www.google.ca/search?q=zynga+scroller+react&oq=zynga+scroller&aqs=chrome.2.69i57j0l3.9969j0j4&client=ms-android-rogers-ca&sourceid=chrome-mobile&espv=1&ie=UTF-8

**Comment by KeKs0r** [comment]
@giantelk Thanks for the input, but I tried several options and solely from a UX view swiper.js feels the most native. I have to admit Zynga Scroller is also very good, but its a little more bare metal and I would need to build components on top of it and I have swiper.js already running with smaller issues.

**Comment by giantelk** [comment]
Swiper.js demos look very nice:
http://www.idangero.us/swiper/demos/#.VQr_GY7F-UQ


On Thu, Mar 19, 2015 at 5:51 AM, Marc Höffl <notifications@github.com>
wrote:

> @giantelk <https://github.com/giantelk> Thanks for the input, but I tried
> several options and solely from a UX view swiper.js feels the most native.
> I have to admit Zynga Scroller is also very good, but its a little more
> bare metal and I would need to build components on top of it and I have
> swiper.js already running with smaller issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JedWatson/touchstonejs/issues/49#issuecomment-83455497>
> .
>



-- 

Cheers,
*Flying Horse Dancing*

**Comment by KeKs0r** [comment]
Thats the reason, why I would like to implement my swiper with swiper.js :)

**Comment by jossmac** [comment]
Ref JedWatson/react-tappable#9
