### ISSUE TITLE
Separate touchstone UI and touchstone application structuring

### ISSUE THREAD

**Issue by dcousens** [touchstonejs/touchstonejs#52]

**Comment by arnold-almeida** [comment]
http://semantic-ui.com/

with a "touchstone" theme

**Comment by dcousens** [comment]
This has been done some what. 

@jossmac what is the status of https://github.com/touchstonejs/touchstonejs-ui?

**Comment by jossmac** [comment]
Not yet begun I'm afraid.

I was hoping to do it the other week when you were in Sydney but commercial stuff got in the way :cry:

**Comment by jossmac** [comment]
There's a bit more to this than meets the eye. As we move each component across, we should:
- evaluate its purpose and necessity
- translate the styles to inline
- implement theming if applicable
