### ISSUE TITLE
consider purejs instead of less

### ISSUE THREAD

**Issue by wiber** [touchstonejs/touchstonejs#55]
FTW

https://speakerdeck.com/vjeux/react-css-in-js

**Comment by JedWatson** [comment]
@jossmac and I have been talking a lot about this, I expect we'll make the switch at some stage but the current priority is feature completion and documentation :)

**Comment by mcwhittemore** [comment]
The team behind the react material-ui implementation has had a bunch of really good conversations around this issue that you might find interesting. [Here is one](https://github.com/callemall/material-ui/issues/30)

**Comment by gregtillbrook** [comment]
duplicate of #8 ?

**Comment by dcousens** [comment]
@gregtillbrook is right, this is an exact duplicate of the original issue.  Closing in favour of.
