### ISSUE TITLE
App.views intentionally exposed?

### ISSUE THREAD

**Issue by dcousens** [touchstonejs/touchstonejs#70]
Hey @JedWatson,

I just wanted to confirm that `this.views` is meant to be exposed on the `App` object?
See [here](https://github.com/touchstonejs/touchstonejs/blob/a4652ac394320361314da261f284fdd0310a5bd3/src/createApp.js#L27).

I [refactored](https://github.com/touchstonejs/touchstonejs/commit/a4652ac394320361314da261f284fdd0310a5bd3) that part of the code because we had 3 different definitions of `views` in the scope.

**Comment by dcousens** [comment]
Also, in accordance with [this](https://facebook.github.io/react/blog/2014/10/14/introducing-react-elements.html#anti-pattern-exporting-factories).

I'm thinking this is an anti-pattern to begin with?  So maybe `this.views` should go, and we just use `React.createElement` as the gods intended it?

**Comment by williamle8300** [comment]
Anything goin' on here?

**Comment by dcousens** [comment]
No longer relevant.

**Comment by williamle8300** [comment]
Can you elaborate or xpost to an issue?

The OP had a good point and I'm just wondering how you guys handled this.

**Comment by dcousens** [comment]
@williamle8300 not sure what you mean?  The original

**Comment by dcousens** [comment]
@williamle8300 on further review, you are right,  `views` is once again being exposed by `createApp`.

ping @JedWatson any reason?

**Comment by jossmac** [comment]
@dcousens @JedWatson safe to close?

**Comment by dcousens** [comment]
Closing in favour of #86
