### ISSUE TITLE
Ionicon required

### ISSUE THREAD

**Issue by dcousens** [touchstonejs/touchstonejs#72]
Is ionicon [really](https://github.com/touchstonejs/touchstonejs/blob/c3a5a6bfdc341587cc96db81a51fd8facb755bf1/less/mixins.less#L43) a necessary dependency?

**Comment by jossmac** [comment]
Some form of icon library is required. Ionicons provide iOS and Android (also a bunch of their own) icons for populating your app; think titlebar, footer, etc.

It'd be nice to provide an option to opt-out and use an alternative in the future though.

If you're talking about that mixin specifically, no it's not required, but it sure is helpful

**Comment by dcousens** [comment]
@jossmac perhaps we could move it out to be a more generic `ionicon` less mixin?

**Comment by supnate** [comment]
+1 for remove the ionicon dependency.

**Comment by jossmac** [comment]
In theory this is a lovely idea; in practice it's much more difficult - the truth is people expect to be up and running in minutes out-of-the-box.

This means as a consumer, my details view with a titlebar is suddenly missing the left chevron from the back button, and i have no idea why.

@supnate do you have any recommendations for how to get around this?

Ping @JedWatson

**Comment by dcousens** [comment]
@jossmac I wonder if we could include it as an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies),  which `touchstonejs-starter` would use.  And we just make it clear in the package.json or in a `post-install` warning that you need to either choose your own,  and include one we provide.

**Comment by supnate** [comment]
@jossmac Thanks for the reply. I use touchstone in an online app only for mobile access but not a hybrid app, so small code size is important. Ionicon is a bit large for my application so it will be nice to remove the dependency. By my analysis, ionicon takes about 300KB(less + ttf) while Touchstone itself only takes about 150KB.

I don't have much experience on icon font but my thought is if we could use a sub set of ion icons in svg format. And embed the svg to the document with corresponding less definitions. It may cost additional effort but I think it helps to reduce code size a lot.

At last, Touchstone is really a perfect library dedicated for mobile UIs and I do appreciate your effort on it and making it open sourced.

Thank you.

**Comment by jossmac** [comment]
@supnate that's an interesting, and wouldn't be too expensive. Out of curiosity do you use many of UI components?

**Comment by morenoh149** [comment]
I'm interested in relaxing the dependency so a user could choose fontawesome instead. Or svgs as @supnate wants

**Comment by JedWatson** [comment]
@jossmac can't we just use svg for the icons that are actually used by the framework components? (e.g the left chevron you mentioned)

**Comment by jossmac** [comment]
@JedWatson agreed. I suggest including, in addition to the back chevron, the standard icons for navigation bars, toolbars and tab bars. See:

- [Standard buttons available for toolbars and navigation bars](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Bars.html#//apple_ref/doc/uid/TP40006556-CH12-SW33)
- [Standard icons for use in the tabs of a tab bar](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Bars.html#//apple_ref/doc/uid/TP40006556-CH12-SW34)

**Comment by supnate** [comment]
@jossmac Currently the app is on early stage so we mainly uses list, navigation framework, form elements now. And we implemented multi-select list named check list while Touchstone seems only have radio list. Also we create a date time picker and here is the screenshot : https://app.box.com/s/jqud83zeulvv7j1yryul5avbjpilzhto
If you are interested I'd like to contribute the date picker to Touchstone.

**Comment by jossmac** [comment]
Dude that's awesome!

We always welcome contribution and would love see PR's for both the multiselect list and the date picker :smile:

**Comment by supnate** [comment]
That's great I'm not doing duplicated works:-D I will create pull requests when they are ready for review.

**Comment by jossmac** [comment]
@supnate any word on this?

**Comment by supnate** [comment]
I was just a bit busy these days so I've not found time to well decouple the components from the project. And since I see another `touchstonejs-ui` project will you maintain all UI components here or in the new project?

**Comment by jossmac** [comment]
All components will be maintained here, in core, until we make the move. We're a bit short on time too :)

**Comment by supnate** [comment]
Ok, thank you @jossmac , I will find time to create PRs soon.

**Comment by pke** [comment]
Icon fonts are not a good, accessible way to display icons anyway. Better use SVG all the way.

**Comment by dcousens** [comment]
@jossmac leave this open/close?

**Comment by jossmac** [comment]
Safe to close
