### ISSUE TITLE
Transition doesn't work from list to detail view

### ISSUE THREAD

**Issue by supnate** [touchstonejs/touchstonejs#73]
When accessing demo.touchstonejs.io using safari on iPhone, there is no transition when clicking a list item to show the detail view. It works well when back from detail to list.

**Comment by dcousens** [comment]
Ping @jossmac,  this is a bug in Safari/React AFAIK.

**Comment by jossmac** [comment]
Argh, again! :) Thanks for the heads up @supnate 

I'm afraid this is an ongoing battle with [WKWebView](https://github.com/Telerik-Verified-Plugins/WKWebView), [CSSTransitionGroup](https://github.com/react-component/css-transition-group), and [react-tappable](https://github.com/JedWatson/react-tappable) - we've verified the bug as originating from some combination of these elements, and while we've had a few small wins we can't quite pin it down.

Luckily however Cheng Lou has recently published [react-motion](https://github.com/chenglou/react-motion) - an animation component based exclusively on JavaScript - we intend to port view transitions to it when we have the time. On a positive note; this will open up the possibility for user input in our animations - think iOS style swipe to go back.

Will keep this thread open and update whenever there is news on this

**Comment by supnate** [comment]
I've not been able to reproduce the issue with the latest `touchstonejs-starter` code from my local build, with either `touchstonejs` master or tag v0.4.2. However,  I resolved a similar issue for my own project following https://github.com/facebook/react/issues/2227 , that is moving transition css to `enter-active`.

**Comment by supnate** [comment]
BTW, I agree that react-motion may be the correct way since transition events are not reliable.

**Comment by jossmac** [comment]
That's interesting - I'll investigate using `enter-active` as an interim solution tomorrow when i'm back at work
