### ISSUE TITLE
Which Flux flavor do you recommend, and why?

### ISSUE THREAD

**Issue by hybrisCole** [touchstonejs/touchstonejs#74]
As the title says :), wondering which one suits for Touchstone.

**Comment by dcousens** [comment]
In [touchstonejs-starter](https://github.com/touchstonejs/touchstonejs-starter/blob/master/src/js/stores/people.js) we just wrap an `EventEmitter` using a uni-directional data flow.
There is no reason you couldn't follow the same design,  but sometimes using common patterns as seen in Flux, Reflux, [and so on](https://github.com/kriasoft/react-starter-kit/issues/22).

If you like using the global `Store` pattern, @JedWatson's [store-prototype](https://github.com/JedWatson/store-prototype) is an excellent example of how this can be done simply and efficiently.

In the end,  this is a personal decision in how you want to structure your application, and the dynamics of your team and environment will matter more than any recommendations we can give you.

Therefore,  I believe,  the official position,  is that we don't recommend any particular design.
