### ISSUE TITLE
Comparison to Reapp

### ISSUE THREAD

**Issue by timuric** [touchstonejs/touchstonejs#76]
As far as I can see http://reapp.io is a very similar project to Touchstone. Is there any major difference between the two?

**Comment by JedWatson** [comment]
Reapp and Touchstone _are_ quite similar; Touchstone was released before reapp but I believe they were both in private development around the same time. We discussed merging the projects a while ago but momentum carried them both in different directions.

I'm not familiar enough with reapp's current status or internals to comment too specifically but although they do similar things, they do them quite differently. While they both include UI component libraries, Touchstone has (I think) more focus on the layout management and view navigation systems, and the overall structure of your application. The themeing systems are also quite different.

If you're assessing the two, I'd recommend looking at the way the sample apps are coded and going with the one that you feel more comfortable working with. Also check current development progress + direction, as that may give you an idea of which is headed in the right direction for your app.

For more context on Touchstone and its future you may be interested in the [talk I gave recently at React Europe](https://youtu.be/ctwmd5L1U_Q) and for a nontrivial app written with it check out our [react europe showcase](http://thinkmill.com.au/react-europe).
