### ISSUE TITLE
How do you test your code during development?

### ISSUE THREAD

**Issue by supnate** [touchstonejs/touchstonejs#77]
I thought there are some sample pages for testing components during development. I even don't find them in .gitignore. So how do you test code then? I know there is touchstonejs-starter but it only depends on npm.

**Comment by jossmac** [comment]
We use a [symlink](https://docs.npmjs.com/cli/link) when developing TouchstoneJS

**Comment by supnate** [comment]
Got it. Looks a pretty good practice. Thanks for the prompt reply!

**Comment by jossmac** [comment]
No problem! :)
