### ISSUE TITLE
The demo (http://touchstonejs.io/) isn't loading the sample data of people

### ISSUE THREAD

**Issue by williamle8300** [touchstonejs/touchstonejs#80]
Check it out: http://touchstonejs.io/

I remember it working a few days ago, but seems to be broken now. I also downloaded `touchstone-starter` and same thing is happening there.

**Comment by williamle8300** [comment]
Nevermind, I guess it's an issue with api.randomuser.me. It seems like the request gets timed-out too early in most cases, so no fake users get populated.

Closing.

**Comment by dcousens** [comment]
@williamle8300 maybe we should add a higher timeout?
