### ISSUE TITLE
Mobile only?

### ISSUE THREAD

**Issue by MMRandy** [touchstonejs/touchstonejs#85]
Is this framework responsive such that both tablet and mobile designs can be accounted for in the same app, with media queries governing the necessary layout changes?  This is where Ionic failed imo.

**Comment by tiptronic** [comment]
Hm... Ionic does that pretty good - and so does touchstonejs

**Comment by MMRandy** [comment]
Ok, nice.  Any examples of this by chance?

**Comment by tiptronic** [comment]
I'm not sure I understand. There are plenty of examples available for download. Just download one and check it out...

**Comment by MMRandy** [comment]
#touchiestonejs

Nevermind, think I just learned everything I need to know from your attitude.  Thx.

**Comment by jossmac** [comment]
Hi @MMRandy,

You're correct, TouchstoneJS is capable of phone + tablet apps based on media queries. I recommend checking out https://github.com/apache/cordova-plugin-device for, when necessary, rendering device or platform specific content rather than using the show/hide method of media queries.

Not sure what was going on in this thread earlier, but I hope you have a good experience on your hybrid journey :)

**Comment by MMRandy** [comment]
Thx for response #jossmac.  We build mobile web apps for large ecommerce companies using standard mobile web techniques (html5, css3, backbone, node).  Looking to make the move to React, and Touchstone appears to be one of the better mobile UI libs I have seen to date. 

I'm still a bit confused on best approach for creating React mobile apps when both Phone and Tablet form factors need to be supported for the same app.  The UX experience will need to be different for the two, but the components will essentially offer the same functionality.  We want to avoid creating separate components that are tailored to each form factor, hence my original question regarding media queries.
 
However, the overall layout and container of the two form factors will obviously need to be different.  This is where I'd like to see how best to handle with Touchstone.  Is the UI experience between phone/tablet just too different to achieve singularity in your component approach?   Or should you develop separate app container components, use device checking to load the appropriate container, which in turn load your app components that "react" responsively to their respective container?

**Comment by JedWatson** [comment]
@MMRandy an approach we've taken with some projects is to create common "inner" components but wrap them in separate application-level scaffolds; so you can customise the overall user experience of the different applications (phone / tablet) but re-use most of the code. This goes for stores / application logic, as well as the UI components; they're most often going to be exactly the same (except, possibly navigation logic).

Whether you do this in two completely separate projects or just branch at a high level based on the device being used would be up to your application design and codebase structure, really.

This is also not a bad approach for cross-platform apps (e.g. Android & iOS) when the overall navigation structure warrants it; although we've often found stylesheets to be enough to implement the differences.

If you do end up going with the "two repos" approach, you can set up your package.json to pull the shared components in from a third repo, or look into npm private modules.

**Comment by MMRandy** [comment]
Thanks @jossmac.  I guess it's that application-level scaffolding that I'm actually searching for.  I've been unable to find anything generic enough to accommodate our needs up to this point, so we're just going to roll our own.  Pretty sure we would not branch the repos, but I guess it would depend on how large your scaffolding becomes.  Thanks again.
