### ISSUE TITLE
Roadmap and timelines 1.0?

### ISSUE THREAD

**Issue by jasperkuperus** [touchstonejs/touchstonejs#87]
Hi! In the search for an alternative to ionic, we've recently stumbled upon Touchstone. I must say, I'm impressed and would really like to embrace React by using Touchstone in our mobile apps.

However, for actually using Touchstone in future production apps, it's important for us to know if you guys are planning to put more work into this. So, is there a roadmap or are there perhaps already some projected timelines?

Furthermore, the only thing we can see here from the outside is the activity on these repos. Are you internally working on Touchstone in a private repo?

**Comment by jossmac** [comment]
Hi @jasperkuperus,

Thanks for your interest in TouchstoneJS - I'll try to answer everything.

**Is there a roadmap?**
There was a roadmap, which included things like:
- inertia scrolling
- solid touch handling
- maintaining scroll-position when navigating views
- iOS style view transitions
- etc.

Though we completed all the tasks in preparation for [React Europe](https://www.react-europe.org), where we were responsible for the [conference app](http://thinkmill.com.au/react-europe) and unfortunately haven't created another.


**Putting more work into this**
Yes, at the very least we intend to document Touchstone in its current state and tidy up some areas for a 1.0.0 release. It's also worth mentioning that [React Native](https://facebook.github.io/react-native/) has made us rethink where TouchstoneJS stands in the React.js/Mobile ecosystem

**Regarding timelines**
For the past few months and the immediate future our focus will be on [Elemental UI](http://elemental-ui.com) and [KeystoneJS](http://keystonejs.com) where we are converting the Admin UI to an SPA using React.js

**Working in a private repo**
For public projects we are completely transparent. The codebase may be split across multiple repos but everything is kept public

**Comment by jossmac** [comment]
Ping @JedWatson anything you would like to add?

**Comment by jasperkuperus** [comment]
Thanks for your elaborate response, @jossmac! I must say, @JedWatson's talk at React Conf made me very enthusiastic. Curious what he has to add to this discussion.

**Comment by thiagofelix** [comment]
Hello!

Thank you @jossmac  for the detailed answer.

Just for curiosity, could you share what is the thinking when looking at the react-native?

One think that I am particularly interested is the deployment/update of apps, which can only happens via app store when running react-native, versus being able to deploy on external url / server when using cordova and hybrid apps.

Thanks!

**Comment by dcousens** [comment]
@thiagofelix you can hot-reload off a web server using react-native AFAIK. @JedWatson ?

**Comment by nvcken** [comment]
@jossmac 
```
It's also worth mentioning that React Native has made us rethink where TouchstoneJS stands in the React.js/Mobile ecosystem
```
IMO touchstonejs (reactjs)  is still have place as same as what ionic framework (angular) does because some people like reactjs + flux/redux than others.

**Comment by nvcken** [comment]
Does Elemental UI and KeystoneJS support responsive layout & touch/ swipe for mobile web ?

**Comment by jossmac** [comment]
@nvcken no, I pointed them out to illustrate where our focus is for the foreseeable future. They are unrelated to TouchstoneJS

PRs are welcome - would you be interested in implementing swipe support?

**Comment by nvcken** [comment]
My first refs for swipe is https://github.com/petehunt/react-touch, I am looking to it right now.
Have any other good refs please tell me?
I read somewhere point out angular2 built for mobile first and have hard focus on mobile touch event & animation, maybe good way to refs for porting to React.js
Thanks

**Comment by jossmac** [comment]
@nvcken react-touch looks good; Pete Hunt's repos are solid

This conversation should be over on #41. Please move your comment and we'll pick it up there :)
