### ISSUE TITLE
Menubar on demo misaligned.

### ISSUE THREAD

**Issue by codeHatcher** [touchstonejs/touchstonejs#88]
![image](https://cloud.githubusercontent.com/assets/5360982/10353771/7adf51d8-6d0e-11e5-814a-e4d7773b10d2.png)

**Comment by jossmac** [comment]
@codeHatcher that's odd. What's the URL?

**Comment by codeHatcher** [comment]
The one linked in the Readme of this repo. I think it was demo.touchstonejs.io

**Comment by jossmac** [comment]
Thanks for the heads up! You can see the current demo at http://touchstonejs.io
