### ISSUE TITLE
Windows Phone support

### ISSUE THREAD

**Issue by pke** [touchstonejs/touchstonejs#91]
Great, simple to use framework and impressive performance of the react-europe app!

Most of what TouchstoneJS offers basically works on IE/Phone. There are some rendering glitches like flickering and so. I wonder if that project is still developed or abandoned in favour of "react native" (which is not available nor needed on Windows Phone, simply because HTML/CSS is a first class citizen on Windows). Before committing our app on this framework I'd like to get an opinion from the owners.
@JedWatson seems to be rarely seen here now.

**Comment by JedWatson** [comment]
@pke not abandoned at all, we've just been in intensive wrap-up mode with some commercial projects and I've been focusing heavily on [keystonejs](http://keystonejs.com) as well for the last two months.

I don't think it will get from us (or needs?) any significant updates in the coming months but Touchstone and hybrid apps are still very relevant despite the growth of React Native, especially for Windows and projects where native (or React Native) is not the best option. We have a number of apps developed with it in production.

We'll be updating it to React 0.14 soon and welcome collaboration, if you want to get involved please do so! Would especially welcome compatibility updates, docs and new features.

**Comment by pke** [comment]
How about support for `react-router`. The issue has not been updated in a while and I cannot see any commit regarding this.
