### ISSUE TITLE
React package as PeerDependency

### ISSUE THREAD

**Issue by thiagofelix** [touchstonejs/touchstonejs#95]
Hi all.

First of all thank you very much for putting touchstonejs together, I really appreciate the work done here.

I am working on #89 and have a question, can we put react-* dependencies as peerDependencies on the package.json, this way we precent things like [Invariant Violation: addComponentAsRefTo](http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean)

Plus we free host projects which import touchstone and its dependencies to upgrade react independently of touchstonejs.

Ultimately we would need to bump the package major version since sorts of introduce a breaking change in the current version.

Thanks

**Comment by pke** [comment]
I'd also appreciate that we could use react 0.14 finally. At the moment it gets compiled twice (one time separate as react.js and one time embedded into app,js)

**Comment by thiagofelix** [comment]
Correct, I am seeing the same problem while trying to run the starter with react-14, another PR is needed there.

**Comment by JedWatson** [comment]
Thanks @thiagofelix! #97 has been merged, so this is resolved now.
