### ISSUE TITLE
Swipe List Items

### ISSUE THREAD

**Issue by der-ede** [touchstonejs/touchstonejs#99]
Hi there,

is there a way to swipe list items as in ionic?

**Comment by jossmac** [comment]
No, not at the moment

**Comment by der-ede** [comment]
Hi @jossmac

I was just wondering since lot of people using reactjs now, what would be the best way of developing a mobile app with react?
I mean I like touchstone being light weight but just some stuff is missing 
Or is there any other mobile framework that's like ionic only for reactjs?

**Comment by jossmac** [comment]
http://reapp.io is also built on React.js

**Comment by der-ede** [comment]
Right, but it's bloody alpha version
Even the demo does neither run on chrome nor on safari on my iPhone


Am Montag, 30. November 2015 schrieb Joss Mackison :

**Comment by pke** [comment]
@jossmac reapp is pretty much dead, since the main author left it.

**Comment by der-ede** [comment]
Hi @philipp,

I think there really is a mobile framework missing that fits to reactjs and
meteor.


Am Montag, 7. Dezember 2015 schrieb Philipp Kursawe :

**Comment by pke** [comment]
I'd hoped touchstonejs would be that framework? It should just be less centered on its views/view managers and more react-router friendly.

**Comment by der-ede** [comment]
Yes, definitely. And maybe some more functionality like swiping of list
items, which I missed it action sheets, unless I oversaw it.
Also F7 looks promising.

Am Montag, 7. Dezember 2015 schrieb Philipp Kursawe :

**Comment by pke** [comment]
Nah, F7 looks only promising but isn't upon further inspection. Instead of using cordova it brings its own platform independence code. And its not using react and operates directly on the DOM.

**Comment by der-ede** [comment]
Then thats crap, nowadays it's just easier to use frameworks that already
exist.
we are doing meteor here and right now meteor ionic but seems to be going
into react direction (blaze 2), or Angular and ionic.


Am Montag, 7. Dezember 2015 schrieb Philipp Kursawe :

**Comment by pke** [comment]
I havent looked at metor yet. But if its going to Angular 2 then you can forget about it.
Nobody would want to go back to Angular after seeing react+redux.

**Comment by der-ede** [comment]
Nono, react. Angular is just supported for people to make the transition
easier.

Am Montag, 7. Dezember 2015 schrieb Philipp Kursawe :

**Comment by der-ede** [comment]
Hi @pke,

I just took a peak at React + Redux and now I see what you mean.
It seems to be really fast in terms of iterating ones own code (hot code push) and state handling, which is appreciable considering developers requirements nowadays.
Meteor also comes with its own hot code push, but it is slower than Redux and the state handling is also not as advanced (mostly done by Session variables that aren't as convenient to handle in Blaze).
But then again, hot code push also pushes new versions of already deployed apps making updating of apps almost obsolete.
Then again, the Meteor system provides a much easier way of connecting all the building blocks, and if I look at webpack, gulp, grunt etc. and the effort I would have to put into that where Meteor handles all the versioning and packaging for me in the background I am glad to go with Meteor.
Also this way new developers can familiarize themselves faster with existing apps.
In the end it's all a matter of development speed and getting things done quickly.
So I stay with Meteor and Blaze, incorporating React and waiting for MDGs integration of React + Redux.
Hope it helps anyone.

Regards

**Comment by morenoh149** [comment]
ReactJS is concerned only with the front-end. To do form validation you should do it in the client and backend as well.

**Comment by der-ede** [comment]
Well, backend would not be a problem in meteor, that's done easily with
allow deny rules. Some react components also come with their own validation
in place.


Am Montag, 14. Dezember 2015 schrieb Harry Moreno :

**Comment by der-ede** [comment]
Hi @Harry, so what Framework would you suggest?

Am Montag, 14. Dezember 2015 schrieb Harry Moreno :
